version: 3

project:
  locator: custom+40901/git@github.com:blackfyre/wga.git

paths:
  exclude:
    - .opencode
    - .claude
    - .agents
    - .fallow
    - .codegraph
    - .vscode
    - .gitnexus
    - dist
    - tmp
    - wga_data
    - wga_sitemap
    - node_modules
