version: 2

project_name: Web Gallery of Art

report_sizes: true

before:
  hooks:
    - bun install
    - bun run build:css
    - bun run build:js
    - go tool templ generate
    - go run ./cmd/generate-licences --application-version={{ .Version }}
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/blackfyre/wga/internal/buildinfo.Version={{ .Version }}

archives:
  - format: tar.gz
    files:
      - dist/wga.cdx.json
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
