version: "3"

services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${WGA_S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${WGA_S3_ACCESS_SECRET}
      - MINIO_ACCESS_KEY=${WGA_S3_ACCESS_KEY}
      - MINIO_SECRET_KEY=${WGA_S3_ACCESS_SECRET}
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    restart: unless-stopped

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set wgaminio http://minio:9000 ${WGA_S3_ACCESS_KEY} ${WGA_S3_ACCESS_SECRET};
      /usr/bin/mc mb wgaminio/${WGA_S3_BUCKET};
      /usr/bin/mc anonymous set public wgaminio/${WGA_S3_BUCKET};
      /usr/bin/mc anonymous set download wgaminio/${WGA_S3_BUCKET};
      exit 0;
      "
    restart: "no"

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    restart: unless-stopped
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    volumes:
      - mailpit:/data

volumes:
  minio:
  mailpit:
