version: "3"

tasks:
  reboot:
    cmds:
      - rm -rf wga_data
      - node esbuild.mjs
      - go run . serve
  start:
    cmds:
      - node esbuild.mjs
      - templ generate
      - go run . serve
  build:frontend:
    cmds:
      - node esbuild.mjs
