// Pinned scenario records from the embedded synthetic fixture
// (resources/synthetic/, generated by wga-src). The seed keeps source record
// IDs, so each path below is exactly what WGA serves after a fresh
// `mise run test:playwright` start. Refresh these values when the fixture is
// regenerated with different scenario records.

// Curated artist with three selections and an "On this page" record layout.
// Used by record-production, release-inventory, and dual-production.
export const curatedArtist = {
	id: "2236bdd57f7492e",
	path: "/artists/synthetic-artist-02-2236bdd57f7492e",
	name: "SYNTHETIC ARTIST 02",
	breadcrumb: "Synthetic Artist 02",
	holdingPath: "/artworks?artist=SYNTHETIC+ARTIST+02",
} as const;

// Selection with sourced commentary.
// Used by record-production, release-inventory, and dual-production.
export const commentarySelection = {
	id: "5ef9746d522357d",
	path: `${curatedArtist.path}/selections/5ef9746d522357d`,
} as const;

// Selection whose commentary is unavailable. Used by record-production.
export const uncommentedSelection = {
	id: "ff3b947b8303fbd",
	path: `${curatedArtist.path}/selections/ff3b947b8303fbd`,
} as const;

// Artwork with all three related-works bases populated: Synthetic Artist 01,
// 1902, held by Synthetic Museum of Fine Arts. It is also the first artwork of
// the palette pair.
// Used by record-production, release-inventory, dual-production,
// artwork-record-relationships-task73, and artwork-palette.
export const relationshipArtwork = {
	id: "2225c982be1af02",
	path: "/artists/synthetic-artist-01-ad32608c6e36b2e/synthetic-artwork-01-01-2225c982be1af02",
	title: "Synthetic Artwork 01-01",
	firstPaletteBand: "#AC83BA, 27% of the surface",
	// One pinned related record per basis.
	sameArtistPath:
		"/artists/synthetic-artist-01-ad32608c6e36b2e/synthetic-artwork-01-02-38311d50a756d76",
	sameCollectionPath:
		"/artists/synthetic-artist-02-2236bdd57f7492e/synthetic-artwork-02-03-96ee4ffe4a2a974",
	samePeriodPath:
		"/artists/synthetic-artist-02-2236bdd57f7492e/synthetic-artwork-02-01-778ed0ab7a62b62",
} as const;

// Second palette artwork by the same artist as relationshipArtwork; every
// synthetic artwork carries a six-band palette. Used by artwork-palette.
export const pairedPaletteArtwork = {
	id: "38311d50a756d76",
	path: relationshipArtwork.sameArtistPath,
} as const;

// Public museum venue offered by the artwork COLLECTION filter.
// Used by artwork-search-task71.
export const museumVenue = {
	id: "da1cec57c285f0d",
	name: "Synthetic Museum of Fine Arts",
} as const;

// Year range over the synthetic artists' lifetimes, strictly inside the fixed
// 200–1900 artwork filter span so neither bound is canonicalised away (the
// synthetic artworks themselves are dated 1902–1911, beyond that span).
// Used by artwork-search-task71.
export const artworkYearRange = { from: "1800", to: "1850" } as const;

// Music record with an embedded audio file. Used by release-inventory.
export const musicSong = {
	id: "72d6bb922f76aea",
	path: "/player?song=72d6bb922f76aea",
} as const;

export function dualPath(left: string, right: string, query = ""): string {
	return `/dual-mode?wide=1&left=${encodeURIComponent(left)}&right=${encodeURIComponent(right)}${query}`;
}
