package constants

const (
	CollectionArtists                      = "artists"
	CollectionArtworks                     = "artworks"
	CollectionSelections                   = "art_selections"
	CollectionArtForms                     = "art_forms"
	CollectionArtTypes                     = "art_types"
	CollectionLocations                    = "locations"
	CollectionContributorRefreshExecutions = "tracking_contributor_refresh_executions"
	CollectionContributorSnapshots         = "tracking_contributor_snapshots"
	CollectionFeedbacks                    = "feedbacks"
	CollectionGuestbook                    = "guestbook"
	CollectionPostcards                    = "postcards"
	CollectionStaticPages                  = "static_pages"
	CollectionStrings                      = "strings"
	CollectionSchools                      = "schools"
	CollectionGlossary                     = "Glossary"
	CollectionTourEditors                  = "guided_tour_editors"
	CollectionGuidedTours                  = "guided_tours"
	CollectionGuidedTourRevisions          = "guided_tour_revisions"
	CollectionGuidedTourSections           = "guided_tour_sections"
	CollectionGuidedTourPages              = "guided_tour_pages"
	CollectionGuidedTourBlocks             = "guided_tour_blocks"
	CollectionGuidedTourIndexRows          = "guided_tour_index_rows"
	CollectionGuidedTourBibliography       = "guided_tour_bibliography"
	CollectionGuidedTourLegacyRoutes       = "guided_tour_legacy_routes"
	CacheGuestbookYears                    = "guestbook:years"
)
