name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.22.0"
      - name: Install a-h/templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Install go modules
        run: go mod tidy
      - name: Compile templates
        run: templ generate
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build the application
        run: go build -o wga
      - name: Run the application
        run: ./wga serve
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
