name: Playwright Tests
on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.templ"
      - "**/*.pcss"
      - ".github/workflows/playwright.yml"
      - "package.json"
      - "bun.lock"
      - "yarn.lock"
      - "go.mod"
      - "go.sum"
      - "mise.toml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.templ"
      - "**/*.pcss"
      - ".github/workflows/playwright.yml"
      - "package.json"
      - "bun.lock"
      - "yarn.lock"
      - "go.mod"
      - "go.sum"
      - "mise.toml"
jobs:
  backend-quality-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
          only_changed: True
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Transpile Frontend
        run: bun run build
      - name: Compile templates
        run: go tool templ generate
      - name: Install go modules
        run: go mod tidy
      - name: Run go vet
        run: go vet ./...
      - name: Run go tests
        run: go test ./... -cover
      - name: Build the application
        run: go build -v -o ./out/wga ./cmd/wga
      - uses: actions/upload-artifact@v4
        with:
          name: wga-binary
          path: out/wga
          retention-days: 1

  build:
    needs: backend-quality-gates
    runs-on: ubuntu-latest
    environment: playwright
    steps:
      - name: Fetch the application binary
        uses: actions/download-artifact@v4
        with:
          name: wga-binary
          path: ./out
      - name: Set executable permissions
        run: chmod +x ./wga
        working-directory: ./out
      - name: Run migrations
        run: ./wga migrate
        working-directory: ./out
        env:
          WGA_ENV: test
          WGA_PROTOCOL: http
          WGA_HOSTNAME: localhost:8090
          WGA_ADMIN_EMAIL: some.random.email@local.host
          WGA_ADMIN_PASSWORD: VerySecurePassword
          WGA_S3_ENDPOINT: http://localhost:9000
          WGA_S3_BUCKET: wga
          WGA_S3_REGION: us-east-1
          WGA_S3_ACCESS_KEY: minio_access_key
          WGA_S3_ACCESS_SECRET: minio_secret_key
          WGA_SMTP_HOST: 127.0.0.1
          WGA_SMTP_PORT: "1025"
          WGA_SMTP_USERNAME: ""
          WGA_SMTP_PASSWORD: ""
          WGA_SENDER_ADDRESS: do-not-reply@wga.hu
          WGA_SENDER_NAME: WGA
          MAILPIT_URL: http://127.0.0.1:8025
      - uses: actions/upload-artifact@v4
        with:
          name: wga
          path: out
          retention-days: 1
  playwright-tests:
    needs: build
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    runs-on: ubuntu-latest
    environment: playwright
    steps:
      - uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Fetch the build artifacts
        uses: actions/download-artifact@v4
        with:
          name: wga
          path: ./wga_tmp
      - name: Download Mailpit
        run: wget -q -O mailpit-linux-amd64.tar.gz https://github.com/axllent/mailpit/releases/download/v1.30.4/mailpit-linux-amd64.tar.gz
      - name: Verify Mailpit archive
        run: echo "e9c104154c22b83ac4c7d19f9d665a5c933585a3caafcd790805d732fa8d03fb  mailpit-linux-amd64.tar.gz" | sha256sum --check --status
      - name: Extract Mailpit
        run: tar -xvf mailpit-linux-amd64.tar.gz
      - name: Run Mailpit
        run: ./mailpit --smtp 127.0.0.1:1025 --listen 127.0.0.1:8025 --log-file mailpit.log &
      - name: Wait for Mailpit
        run: for i in {1..30}; do curl --fail --silent --show-error http://127.0.0.1:8025/readyz && exit 0; sleep 1; done; exit 1
      - name: Install Bun dependencies
        run: bun install
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(grep '@playwright/test@' yarn.lock | awk -F'[@"]' '{print $4}' | awk -F'^' '{print $2}')" >> $GITHUB_ENV
      # - name: Cache playwright binaries
      #   uses: actions/cache@v4
      #   id: playwright-cache
      #   with:
      #     path: |
      #       ~/.cache/ms-playwright
      #     key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - run: bunx playwright install --with-deps
        name: Install Playwright
        # if: steps.playwright-cache.outputs.cache-hit != 'true'
      - run: bunx playwright install-deps
        name: Install Playwright dependencies
        # if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Add executable permissions
        run: chmod +x ./wga
        working-directory: ./wga_tmp
      - name: Run the application
        run: ./wga serve > wga.log &
        working-directory: ./wga_tmp
        env:
          WGA_ENV: test
          WGA_PROTOCOL: http
          WGA_HOSTNAME: localhost:8090
          WGA_ADMIN_EMAIL: some.random.email@local.host
          WGA_ADMIN_PASSWORD: VerySecurePassword
          WGA_S3_ENDPOINT: http://localhost:9000
          WGA_S3_BUCKET: wga
          WGA_S3_REGION: us-east-1
          WGA_S3_ACCESS_KEY: minio_access_key
          WGA_S3_ACCESS_SECRET: minio_secret_key
          WGA_SMTP_HOST: 127.0.0.1
          WGA_SMTP_PORT: "1025"
          WGA_SMTP_USERNAME: ""
          WGA_SMTP_PASSWORD: ""
          WGA_SENDER_ADDRESS: do-not-reply@wga.hu
          WGA_SENDER_NAME: WGA
          MAILPIT_URL: http://127.0.0.1:8025
      - name: Wait for the application to start
        run: sleep 5
      - name: Run Playwright tests
        run: bunx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          MAILPIT_URL: http://127.0.0.1:8025
          WGA_PROTOCOL: ${{ vars.WGA_PROTOCOL }}
          WGA_HOSTNAME: ${{ vars.WGA_HOSTNAME }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mailpit-${{ matrix.shardIndex }}
          path: mailpit.log
          retention-days: 1
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: wga-log-${{ matrix.shardIndex }}
          path: wga.log
          retention-days: 1
  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: >-
      ${{
        always() &&
        (needs.playwright-tests.result == 'success' ||
         needs.playwright-tests.result == 'failure')
      }}
    needs: [playwright-tests]
    environment: playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: bunx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14
